#### Manipulando objetos de 3 e 4 dimensões

### As dimensões não se não por linhas, colunas ou profundidades, 
### As dimensões se dão pelo nível das camadas de arrays
[] ---> 1º dimensão <br>
[[]] ---> 2º dimensão <br>
[[[]]] ---> 3º dimensão <br>
[[[[]]]] ---> 4º dimensão <br>
<br>
e assim por diante

In [1]:
import numpy as np

### Começando com um exemplo de 3 dimensões

* Profundidade: Refere-se ao número de listas externas, ou seja, o número de matrizes ou "camadas" que temos. No exemplo fornecido, temos duas listas externas, então a profundidade é 2.

* Linha: Refere-se ao número de listas dentro de cada matriz ou "camada". Cada uma dessas listas representa uma linha na matriz. No exemplo, dentro de cada lista externa, temos três listas internas, então o número de linhas é 3.

* Coluna: Refere-se ao número de elementos em cada lista interna, que representam as colunas na matriz. No exemplo, cada lista interna tem quatro elementos, então o número de colunas é 4.

In [6]:
### Criamos uma lista de listas, que contém listas dentro
array1 = np.array([
   [
       [1,2,3,4],
       [3,4,5,6],
       [3,4,6,2]
   ],
   [
       [4,78,9,52],
       [98,3,6,877],
       [87,4,8,98]
   ]
])

In [7]:
print(array1)

[[[  1   2   3   4]
  [  3   4   5   6]
  [  3   4   6   2]]

 [[  4  78   9  52]
  [ 98   3   6 877]
  [ 87   4   8  98]]]


In [10]:
### O que temos neste objeto é:
### 2 de profundidade
### 3 Linhas
### 4 colunas em cada linha
print(array1.shape)


(2, 3, 4)


In [11]:
print(np.ndim(array1))

3


#### Filtrar objeto de 3 dimensões

In [9]:
### 1º número é o elemento
### 2º número é a linha
### 3º é a coluna
print(array1[0, 1, 2])

5


#### Objeto de 4 dimensões

In [55]:
array2 = np.array([
    [
        [
            [2,3,4,5],
            [4,52,4,2]
        ], 
        [
            [2,3,4,5],
            [4,52,4,2]
        ]
    ],
    [
        [
            [24,33,45,555],
            [45,525,45,255]
        ], 
        [
            [22,22,42,52],
            [42,522,422,22]
        ]
    ],
])

In [56]:
print(np.ndim(array2))

4


In [57]:
print(array2[1, 1, 1, 2])

422


### Objeto de 5 dimensões

In [58]:
array3 = np.array(
    [
        [
            [
                [
                    [2,3,4,5],
                    [4,52,4,2]
                ],
                [
                    [9,36,48,58],
                    [47,59,46,99]
                ],
                [
                    [22,31,41,51],
                    [41,52,41,21]
                ],
            ]
        ]
    ]
)

In [59]:
print(np.ndim(array3))

5


In [66]:
print(array3[0, 0, 1, 1, 2])

46


### Então veja, eu só tenho objetos apartir do nível 3, do qual no 3º eu tenho 3 objetos, que posso escolher entre seus indíces, agora abaixo veja um exemplo preenchedo todas as 5 dimensões

In [81]:
array4 = np.array(
    [
        [
            [
                [
                    [2,3,4,5],
                    [52,36,43,545]
                ],
                [
                    [24,34,44,54],
                    [2345,3434,4467,546]
                ]
            ],
            [
                [
                    [2534,3555,45,5523],
                    [2533,35345,4534,5563]
                ],
                [
                    [2675,36563,4634,25634],
                    [2634,3546,45266,7756]
                ]
            ]
        ],
        [
            [
                [
                    [21347,3347,4757,5567],
                    [2345,36737,487,556767]
                ],
                [
                    [278,378,478,58],
                    [27,35,64,58]
                ]
            ],
            [
                [
                    [223,343,453,523],
                    [254,346,477,5445]
                ],
                [
                    [2234,353,4534,5234],
                    [2456,334,444,523]
                ]
            ]
        ],
    ]
)

In [88]:
print(array4.shape)

(2, 2, 2, 2, 4)


In [82]:
print(array4)

[[[[[     2      3      4      5]
    [    52     36     43    545]]

   [[    24     34     44     54]
    [  2345   3434   4467    546]]]


  [[[  2534   3555     45   5523]
    [  2533  35345   4534   5563]]

   [[  2675  36563   4634  25634]
    [  2634   3546  45266   7756]]]]



 [[[[ 21347   3347   4757   5567]
    [  2345  36737    487 556767]]

   [[   278    378    478     58]
    [    27     35     64     58]]]


  [[[   223    343    453    523]
    [   254    346    477   5445]]

   [[  2234    353   4534   5234]
    [  2456    334    444    523]]]]]


In [83]:
print(np.ndim(array4))

5


#### Quanto mais eu fatio, mais fundo na dimensão eu vou
#### Quando menos eu fatio, mais superficial vou na dimensão

In [91]:
#### Este resultado é o máximo que posso ir na dimensão, me trazendo exatamente
#### o Item da última camada
print(array4[1, 1, 1, 1, 2])

444


In [92]:
#### aqui ele me traz a linha completa
print(array4[1, 1, 1, 1])

[2456  334  444  523]


In [93]:
### E assim por diante
print(array4[1, 1, 1])

[[2234  353 4534 5234]
 [2456  334  444  523]]


In [94]:
### E assim por diante
print(array4[1, 1])

[[[ 223  343  453  523]
  [ 254  346  477 5445]]

 [[2234  353 4534 5234]
  [2456  334  444  523]]]


In [95]:
### E assim por diante
print(array4[1])

[[[[ 21347   3347   4757   5567]
   [  2345  36737    487 556767]]

  [[   278    378    478     58]
   [    27     35     64     58]]]


 [[[   223    343    453    523]
   [   254    346    477   5445]]

  [[  2234    353   4534   5234]
   [  2456    334    444    523]]]]


In [98]:
### Até eu mostrar a dimensão por inteiro, tendo uma visão geral dela
print(array4)

[[[[[     2      3      4      5]
    [    52     36     43    545]]

   [[    24     34     44     54]
    [  2345   3434   4467    546]]]


  [[[  2534   3555     45   5523]
    [  2533  35345   4534   5563]]

   [[  2675  36563   4634  25634]
    [  2634   3546  45266   7756]]]]



 [[[[ 21347   3347   4757   5567]
    [  2345  36737    487 556767]]

   [[   278    378    478     58]
    [    27     35     64     58]]]


  [[[   223    343    453    523]
    [   254    346    477   5445]]

   [[  2234    353   4534   5234]
    [  2456    334    444    523]]]]]
