#### Continuação da manipulação de matrizes com Numpy

In [1]:
import numpy as np

In [19]:
list1 = np.array([[4,33,5,3], [3,3,6,8], [3,5,10,5]])

In [20]:
ma = np.matrix(list1)

In [21]:
print(ma)

[[ 4 33  5  3]
 [ 3  3  6  8]
 [ 3  5 10  5]]


##### Indexação de matriz

Na indexação não podemos esquecer que o primeiro argumento é o valor da linha,
Já o segundo argumento é o valor da coluna

Nunca podemos esquecer que os indíces começam com a posição 0

In [6]:
print(ma)

[[ 4 33  5  3]
 [ 3  3  6  8]
 [ 3  5 10  5]]


In [8]:
### Print o valor da lista 1, com o item no indice 2
print(list1[1, 2])

6


In [12]:
# Mostrar da linha 0 até a 3 ( se eu colocar 2 lembre-se que o valor final é anulado então ele vai retornar
# de 0 até a linha 1)
# Então quero da linha 0 até a 3, me mostrando a coluna na posição 1 de cada linha
print(list1[0:3,1])

[33  3  5]


In [13]:
#### Outra forma de mostrar o valor da última posição solicitada ao inves de colocar 3 
### para mostrar a linha, 0,1,2 eu posso acrescentar +1
### que traz o mesmo resultado do de cima
### porém se eu não solber quantas linhas eu tenho em uma matriz, eu posso colocar +1 se eu quiser retornar
### o último valor também
print(list1[0:2+1,1])

[33  3  5]


In [15]:
print(list1[1,]) ### traz todas as colunas do indice 1

[3 3 6 8]


##### Alterando um item na matriz

In [22]:
print(list1)

[[ 4 33  5  3]
 [ 3  3  6  8]
 [ 3  5 10  5]]


In [23]:
### na lista 1, na coluna 2, altere o item para 48
list1[1,2] = 48

In [24]:
print(list1)

[[ 4 33  5  3]
 [ 3  3 48  8]
 [ 3  5 10  5]]


#### dtype para forçar o tipo do dado

Por padrão o numpy tenta descobrir o tipo de dado que existe 
mas podemos definir isto para ele

In [29]:
### Aqui nessas duas listas estamos deixando ele descobrir
list2 = np.array([1,2,3])
list3 = np.array([1,5,3])

In [34]:
print(list2, list3)

[1 2 3] [1 5 3]


In [30]:
#### visualizar o tipo
print(list2.dtype, list3.dtype)

int64 int64


In [31]:
### agora vamos definir o tipo
list4 = np.array([2,4,5], dtype=float)

In [35]:
### Após definir o tipo acima, imprimos o tipo da lista
### Ele tornar float mesmo a lista sendo do tipo int, pois estou definido para ele
### que quero valores float para essa lista
### Veja que ele retorna com um "ponto" no fim pois se traga de um número float

print(list4.dtype)
print(list4)

float64
[2. 4. 5.]


##### itemsize

retornar o tamanho em bytes de cada elemento do array, em outras palavras é o tamanho que vai ser ocupado na memória do computador

In [37]:
print(list2)

[1 2 3]


In [39]:
#### CADA ITEM VAI OCUPAR O VALOR DE 8 BYTES
print(list2.itemsize)

8


In [41]:
### SE EU TENHO NA LISTA ACIMA 3 ITENS, CADA ITEM OCUPA 8 BYTES, 
### 8 bytes * 3 ( quantidade de itens )
print(list2.nbytes)

24


In [42]:
### podemos verificar também o número de dimensões
print(list2.ndim)

1
