### Manipulando matrizes com Numpy

In [2]:
import numpy as np

In [3]:
#### SE eu criar uma lista de listas o numpy entende que é uma matriz
list1 = np.array([[1,2,3,4], [5,6,7,8]])

In [4]:
print(type(list1))

<class 'numpy.ndarray'>


In [5]:
print(list1)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
### Posso verificar a dimensão
print(list1.shape)

(2, 4)


##### Método ones

cria uma matriz de 1's

In [9]:
### 2 dimensões
### 4 itens em cada dimenção
list2 = np.ones((2,4))

In [10]:
print(list2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(type(list2))

<class 'numpy.ndarray'>


In [12]:
print(list2.shape)

(2, 4)


In [13]:
list3 = np.ones((3,5))

In [14]:
## 3 dimensões com 5 itens em cada dimensão
print(list3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### Função Matrix

cria uma matriz em numpy

In [15]:
list5 = np.array([[1,2,4,5], [2,5,3,1], [4,8,4,8]])

In [16]:
print(type(list5))

<class 'numpy.ndarray'>


In [19]:
### Criando uma matriz baseada no array acima
ma = np.matrix(list5)

In [23]:
### ma é do tipo matrix
print(type(ma))

<class 'numpy.matrix'>


In [18]:
print(ma)

[[1 2 4 5]
 [2 5 3 1]
 [4 8 4 8]]


In [21]:
#### Vamos verificar as dimensões
print(ma.shape)

(3, 4)


##### Size

podemos verificar o tamanho da matriz
Esse método nos permite contar quantos elementos tem dentro da matriz, ele literalmente conta quantos itens tem dentro de uma matriz

In [26]:
print(list3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
print(list3.size)

15


In [25]:
print(list2.size)

8


##### Tipos dtype

Os tipos int16, int32 e int64 diferem principalmente em relação ao número de bits que podem ser usados para armazenar um número inteiro. Aqui está uma comparação simples:

    int16:
        Usa 16 bits para armazenar um número inteiro.
        Faixa de valores: -32,768 a 32,767 (incluindo zero).

    int32:
        Usa 32 bits para armazenar um número inteiro.
        Faixa de valores: -2,147,483,648 a 2,147,483,647 (incluindo zero).

    int64:
        Usa 64 bits para armazenar um número inteiro.
        Faixa de valores: -9,223,372,036,854,775,808 a 9,223,372,036,854,775,807 (incluindo zero).

##### Porém não vamos utilizar o dtype para isto, vamos utilizar o dtype para saber
##### Se a matriz é feita de números inteiros, números float, string ou boolean, ou qualquer
##### Outro type

In [29]:
##### A list5 é feito de números inteiros
print(list5.dtype)

int64
