### Funções Numpy

In [1]:
import numpy as np

In [2]:
#### É o mesmo método de python puro o range() de criar uma lista
#### os parametros são (start, stop, step)
### O valor final do indice nao entra na contagem,porque é exclusivo
lts2 = np.arange(0, 20, 2)

In [3]:
print(lts2)

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
#### Visualizar o shape com o python puro
lts2.shape

(10,)

In [5]:
#### VIsualizar o shape com o numpy
np.shape(lts2)

(10,)

In [6]:
#### o tipo do dado
print(lts2.dtype)

int64


In [8]:
### ou esse tipo
print(type(lts2))

<class 'numpy.ndarray'>


##### Criar uma ARRAY preenchida com ZEROS


In [9]:
list3 = np.zeros(10)

In [10]:
print(list3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### Retornar uma matriz com 1 na posição DIAGONAL e o restante preenche com zeros

In [35]:
### o 1º número é a quantidade de linhas
#### o 2º número é a quantidade de itens por linha
#### o 3º número muda a posição de inicio do primeiro número 1 e automaticamente toda a diagonal muda também
list4 = np.eye(3, 4, 2)

In [36]:
print(list4)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [44]:
#### Também posso utilizar outros números para preencher essa diagonal
#### Utilizando o método diag
#### Vamos utilizar uma array para preencher essa array diagonal
list5 = np.diag(np.array([1,2,3,4,5]))

In [45]:
print(list5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### Linspace

Utilizado para criar uma sequência de número igualmente espaçados dentro de um intervalo

É utilizado para gráficos etc

In [49]:
print(np.linspace(1,10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


##### logspace

utilizado para criar uma sequência de números igualmente espaçados em escala logarítma

In [55]:
print(np.logspace(0.1, 1))

[ 1.25892541  1.31331029  1.37004456  1.42922973  1.49097166  1.5553808
  1.62257239  1.69266662  1.76578887  1.84206997  1.92164637  2.00466042
  2.09126064  2.18160194  2.27584593  2.3741612   2.47672365  2.58371673
  2.69533186  2.8117687   2.93323554  3.05994969  3.19213781  3.33003639
  3.47389211  3.62396232  3.78051548  3.94383164  4.11420298  4.29193426
  4.47734343  4.67076218  4.87253651  5.08302738  5.30261134  5.5316812
  5.77064675  6.01993548  6.27999335  6.55128557  6.83429746  7.12953531
  7.43752728  7.75882432  8.09400122  8.44365757  8.80841888  9.18893768
  9.58589468 10.        ]


In [52]:
print(np.logspace(0,10))

[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [54]:
print(np.logspace(0, 10, 15))

[1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]
